-- Waitlist + analytics setup for Dialed (run in Supabase SQL Editor)
-- Table: waitlist_signups
-- RPC: get_waitlist_analytics() — aggregate stats only (emails never exposed to anon)

create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  referrer text,
  created_at timestamptz not null default now()
);

create index if not exists idx_waitlist_signups_created_at
  on public.waitlist_signups (created_at desc);

alter table public.waitlist_signups enable row level security;

drop policy if exists "Allow anonymous inserts" on public.waitlist_signups;
create policy "Allow anonymous inserts"
  on public.waitlist_signups
  for insert
  to anon
  with check (true);

drop policy if exists "Allow authenticated inserts" on public.waitlist_signups;
create policy "Allow authenticated inserts"
  on public.waitlist_signups
  for insert
  to authenticated
  with check (true);

-- Aggregates only; SECURITY DEFINER reads rows without granting SELECT to clients
create or replace function public.get_waitlist_analytics()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  result json;
begin
  select json_build_object(
    'total', (select count(*)::int from waitlist_signups),
    'today', (
      select count(*)::int from waitlist_signups
      where (created_at at time zone 'utc')::date = (now() at time zone 'utc')::date
    ),
    'last_7_days', (
      select count(*)::int from waitlist_signups
      where created_at >= (now() at time zone 'utc') - interval '7 days'
    ),
    'by_source', coalesce((
      select json_agg(
        json_build_object('source', coalesce(source, '(none)'), 'count', cnt)
        order by cnt desc
      )
      from (
        select source, count(*)::int as cnt
        from waitlist_signups
        group by source
      ) s
    ), '[]'::json),
    'daily_last_7', coalesce((
      with days as (
        select generate_series(
          (date_trunc('day', now() at time zone 'utc')::date - 6),
          (date_trunc('day', now() at time zone 'utc')::date),
          interval '1 day'
        )::date as day
      ),
      counts as (
        select
          (date_trunc('day', created_at at time zone 'utc'))::date as day,
          count(*)::int as c
        from waitlist_signups
        where created_at >= (date_trunc('day', now() at time zone 'utc') - interval '6 days')
        group by 1
      )
      select json_agg(
        json_build_object('day', d.day::text, 'count', coalesce(c.c, 0))
        order by d.day
      )
      from days d
      left join counts c on c.day = d.day
    ), '[]'::json)
  ) into result;

  return result;
end;
$$;

grant execute on function public.get_waitlist_analytics() to anon, authenticated;
